required = ["github.com/onsi/ginkgo/ginkgo", "github.com/maxbrunsfeld/counterfeiter"]

[prune]
  unused-packages = true
  non-go = true
  go-tests = true

[[constraint]]
  name = "github.com/coredns/coredns"
  source = "github.com/bosh-dep-forks/coredns"
  branch = "bosh-develop"
