---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/dns-release
    tag: performance-tests

inputs:
  - name: bosh-dns-release

run:
  path: bosh-dns-release/ci/tasks/test-performance.sh
