---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-ruby-go

inputs:
  - name: dns-release
  - name: bbl-cli
  - name: bosh-cli
  - name: bosh-deployment
  - name: bosh-candidate-stemcell-windows
  - name: bosh-candidate-release

params:
  BBL_AWS_ACCESS_KEY_ID:
  BBL_AWS_SECRET_ACCESS_KEY:
  BBL_AWS_REGION: us-east-1
  BBL_IAAS: aws

run:
  path: dns-release/ci/tasks/test-acceptance-windows.sh
