---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-ruby-go

inputs:
  - name: dns-release
  - name: bbl-state
  - name: bosh-candidate-stemcell-windows

run:
  path: dns-release/ci/tasks/test-acceptance-windows-nameserver-disabled.sh
