---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
  - name: dns-release

params: []

run:
  path: dns-release/ci/tasks/test-acceptance.sh