jobs:
- name: build-performance-tests-image
  public: true
  serial: true
  plan:
  - aggregate:
    - get: repo
      trigger: true
  - put: performance-tests-image
    params:
      build: "repo/ci/docker/performance-tests"
    get_params:
      skip_download: true
- name: build-acceptance-tests-image
  public: true
  serial: true
  plan:
  - aggregate:
    - get: repo
      trigger: true
    - get: main-bosh-docker-image
      trigger: true
      params:
        skip_download: true
  - put: acceptance-tests-image
    params:
      build: "repo/ci/docker/acceptance-tests"
    get_params:
      skip_download: true
- name: build-acceptance-tests-windows-image
  public: true
  serial: true
  plan:
  - get: repo
    trigger: true
  - put: acceptance-tests-windows-image
    params:
      build: "repo/ci/docker/acceptance-tests-windows"
    get_params:
      skip_download: true
resources:
- name: repo
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-dns-release.git
    branch: master
    paths:
    - "ci/docker"
- name: main-bosh-docker-image
  type: docker-image
  source:
    repository: bosh/main-bosh-docker
- name: performance-tests-image
  type: docker-image
  source:
    repository: bosh/bosh-dns-release
    tag: performance-tests
    email: {{dockerhub_email}}
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
- name: acceptance-tests-image
  type: docker-image
  source:
    repository: bosh/bosh-dns-release
    tag: acceptance-tests
    email: {{dockerhub_email}}
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
- name: acceptance-tests-windows-image
  type: docker-image
  source:
    repository: bosh/bosh-dns-release
    tag: acceptance-tests-windows
    email: {{dockerhub_email}}
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
