---
name: bosh-dns

update:
  canaries: 1
  canary_watch_time: 30000-1200000
  max_in_flight: 5
  serial: false
  update_watch_time: 5000-1200000

instance_groups:
- name: dns
  azs: [z1,z2]
  instances: 1
  vm_type: default
  stemcell: default
  networks:
  - name: default
    static_ips: [10.245.0.34]
  jobs:
  - name: dns
    release: dns
  - name: needs-alias
    release: alias-providing
  properties:
    address: 0.0.0.0
    recursors:
    - 8.8.8.8

releases:
- name: dns
  url: file://((dns_release_path))
  version: create
- name: alias-providing
  url: file://((alias_release_path))
  version: create

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest
