---
name: bosh-dns

update:
  canaries: 2
  canary_watch_time: 1000-60000
  max_in_flight: 5
  serial: false
  update_watch_time: 1000-60000

instance_groups:
- name: dns
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks:
  - name: default
    static_ips: [10.245.0.34]
  jobs:
  - name: dns
    release: dns
  - name: needs-alias
    release: dns-acceptance
  properties:
    address: 0.0.0.0
    recursors:
    - 8.8.8.8

releases:
- name: dns
  url: file://((dns_release_path))
  version: create
- name: dns-acceptance
  url: file://((acceptance_release_path))
  version: create

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest
