---
name: bosh-dns

update:
  canaries: 2
  canary_watch_time: 1000-60000
  max_in_flight: 5
  serial: false
  update_watch_time: 1000-60000

instance_groups:
- name: bosh-dns
  azs: [z1]
  instances: 2
  vm_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: needs-alias
    release: dns-acceptance
  - name: bosh-dns
    release: bosh-dns
    properties:
      address: 0.0.0.0
      recursors:
      - "172.17.0.1:9955"
      recursor_timeout: 1s

releases:
- name: bosh-dns
  version: latest
- name: dns-acceptance
  url: file://((acceptance_release_path))
  version: create

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest
