---
name: bosh-dns-windows-acceptance

update:
  canaries: 5
  canary_watch_time: 30000-120000
  max_in_flight: 5
  serial: false
  update_watch_time: 30000-120000

instance_groups:
- name: dns-no-system-caching
  azs: [z1]
  instances: 1
  vm_type: large
  vm_extensions:
  - 100GB_ephemeral_disk
  stemcell: default
  networks:
  - name: private
  jobs:
  - name: acceptance-tests-windows
    release: bosh-dns
    properties:
      properties_to_test:
        os_caching_enabled: false
  - name: bosh-dns-windows
    release: bosh-dns
    properties:
      enable_os_dns_caching: false

- name: dns-with-system-caching
  azs: [z1]
  instances: 1
  vm_type: large
  vm_extensions:
  - 100GB_ephemeral_disk
  stemcell: default
  networks:
  - name: private
  jobs:
  - name: acceptance-tests-windows
    release: bosh-dns
    properties:
      properties_to_test:
        os_caching_enabled: true
  - name: bosh-dns-windows
    release: bosh-dns
    properties:
      enable_os_dns_caching: true


releases:
- name: bosh-dns
  version: latest

stemcells:
- alias: default
  os: ((windows_stemcell))
  version: latest
