---
name: bosh-dns-windows-acceptance

update:
  canaries: 5
  canary_watch_time: 30000-120000
  max_in_flight: 5
  serial: false
  update_watch_time: 30000-120000

instance_groups:
- name: acceptance-tests-windows
  azs: [z1]
  instances: 1
  vm_type: large
  vm_extensions:
  - 100GB_ephemeral_disk
  stemcell: default
  lifecycle: errand
  networks:
  - name: private
  jobs:
  - name: dns-windows
    release: dns
  - name: acceptance-tests-windows
    release: dns

releases:
- name: dns
  version: latest

stemcells:
- alias: default
  os: windows2012R2
  version: latest
