---
jobs:
- name: test-unit
  public: true
  plan:
    - get: dns-release
      trigger: true
    - task: test-unit
      file: dns-release/ci/tasks/test-unit.yml

- name: test-performance
  public: true
  plan:
    - get: dns-release
      trigger: true
      passed: [test-unit]
    - task: test-performance
      privileged: true
      file: dns-release/ci/tasks/test-performance.yml

- name: test-acceptance
  public: true
  plan:
    - get: dns-release
      trigger: true
      passed: [test-unit]
    - task: test-acceptance
      privileged: true
      file: dns-release/ci/tasks/test-acceptance.yml

resources:
- name: dns-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/dns-release
    branch: master
