---
jobs:
- name: test-unit
  public: true
  plan:
    - get: dns-release
      trigger: true
    - task: test-unit
      file: dns-release/ci/tasks/test-unit.yml

- name: test-performance
  public: true
  plan:
    - get: dns-release
      trigger: true
      passed: [test-unit]
    - task: test-performance
      privileged: true
      file: dns-release/ci/tasks/test-performance.yml

- name: test-acceptance
  public: true
  plan:
    - get: dns-release
      trigger: true
      passed: [test-unit]
    - get: bosh-candidate-stemcell
    - get: bosh-candidate-release
    - task: test-acceptance
      privileged: true
      file: dns-release/ci/tasks/test-acceptance.yml

resources:
- name: dns-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/dns-release
    branch: master

- name: bosh-candidate-stemcell
  type: s3
  source:
    bucket: bosh-core-stemcells-candidate
    regexp: warden/bosh-stemcell-(.+)-warden-boshlite-ubuntu-trusty-go_agent.tgz

- name: bosh-candidate-release
  type: s3
  source:
    bucket: bosh-candidate-release-tarballs
    versioned_file: bosh-dev-release.tgz