---
jobs:
- name: test-unit
  public: true
  plan:
    - get: bosh-dns-release
      trigger: true
    - task: test-unit
      file: bosh-dns-release/ci/tasks/test-unit.yml

- name: test-unit-windows
  public: true
  plan:
    - get: bosh-dns-release
      trigger: true
    - task: test-unit-windows
      file: bosh-dns-release/ci/tasks/test-unit-windows.yml

- name: test-performance
  public: true
  serial: true
  plan:
    - get: every-10m
      trigger: true
    - get: bosh-dns-release
      trigger: true
      passed: [test-unit]
    - task: test-performance
      tags: ["dns-performance"]
      privileged: true
      file: bosh-dns-release/ci/tasks/test-performance.yml
      params:
        ZONES_JSON_HASH: {{zones_json_hash}}

- name: test-acceptance
  public: true
  serial: true
  plan:
    - get: every-2h
      trigger: true
    - get: bosh-dns-release
      trigger: true
      passed: [test-unit]
    - get: bosh-candidate-stemcell
    - get: bosh-candidate-release
    - task: test-acceptance
      privileged: true
      file: bosh-dns-release/ci/tasks/test-acceptance.yml

- name: test-acceptance-windows
  public: true
  serial: true
  serial_groups:
  - windows-acceptance-env
  plan:
    - get: every-2h
      trigger: true
    - get: bosh-dns-release
      trigger: true
      passed: [test-unit-windows]
    - get: envs
    - get: bosh-deployment
    - get: gcp-linux-stemcell
    - get: bosh-candidate-stemcell-windows
    - get: bosh-candidate-release
    - task: windows
      file: bosh-dns-release/ci/tasks/test-acceptance-windows.yml
    - task: windows-nameserver-disabled
      file: bosh-dns-release/ci/tasks/test-acceptance-windows-nameserver-disabled.yml
    - task: windows-shared
      file: bosh-dns-release/ci/tasks/test-acceptance-windows-shared.yml
    - task: clean-up
      file: bosh-dns-release/ci/tasks/clean-up.yml

- name: brats-ubuntu
  plan:
  - do:
    - aggregate:
      - get: bosh-src
      - get: dns-release
        resource: bosh-dns-release
        trigger: true
        passed: [test-unit]
      - get: candidate-warden-ubuntu-stemcell
        resource: bosh-candidate-stemcell
      - get: bosh-release
    - task: test-brats
      file: bosh-src/ci/tasks/test-brats.yml
      tags: ["worker-brats"]
      privileged: true
      params:
        BOSH_DIRECTOR_RELEASE_PATH: "bosh-release/release.tgz"
        BOSH_DIRECTOR_RELEASE_VERSION: "latest"
        DNS_RELEASE_FILE_PATH: "dns-release"
        DNS_RELEASE_VERSION: "create"


- name: bbl-up
  serial: true
  serial_groups:
  - windows-acceptance-env
  plan:
    - get: bosh-dns-release
    - get: bosh-deployment
    - get: bosh-candidate-release
    - get: envs
    - task: bbl-up
      file: bosh-dns-release/ci/tasks/bbl-up.yml
      params:
        BBL_GCP_SERVICE_ACCOUNT_KEY: {{bbl_gcp_service_account_key_id}}
      ensure:
        put: envs
        params:
          repository: envs

- name: bbl-destroy
  serial: true
  serial_groups:
  - windows-acceptance-env
  plan:
    - get: bosh-dns-release
    - get: envs
    - task: bbl-destroy
      file: bosh-dns-release/ci/tasks/bbl-destroy.yml
      params:
        BBL_GCP_SERVICE_ACCOUNT_KEY: {{bbl_gcp_service_account_key_id}}
      ensure:
        put: envs
        params:
          repository: envs

resources:
- name: bosh-dns-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-dns-release
    branch: master
    ignore_paths:
    - ci/docker

- name: bosh-src
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh
    branch: master
    ignore_paths:
    - ci/docker

- name: bosh-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/bosh

- name: bosh-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-deployment
    branch: master

- name: bosh-candidate-stemcell
  type: s3
  source:
    bucket: bosh-core-stemcells-candidate
    regexp: warden/bosh-stemcell-(.+)-warden-boshlite-ubuntu-trusty-go_agent.tgz

- name: bosh-candidate-stemcell-windows
  type: s3
  source:
    bucket: bosh-windows-stemcells-release-candidates
    regexp: light-bosh-stemcell-(.+)-google-kvm-windows2012R2-go_agent.tgz

- name: bosh-candidate-release
  type: s3
  source:
    bucket: bosh-candidate-release-tarballs
    versioned_file: bosh-dev-release.tgz

- name: gcp-linux-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-trusty-go_agent

- name: envs
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/dns-release-ci-envs.git
    private_key: {{envs_private_key}}

- name: every-2h
  type: time
  source: {interval: 2h}

- name: every-10m
  type: time
  source: {interval: 10m}
