---
groups:
- name: all
  jobs:
  - test-acceptance-windows2012
  - test-acceptance-windows2016

jobs:
- name: test-acceptance-windows2012
  public: false
  serial: true
  serial_groups:
  - windows-acceptance-env
  plan:
    - aggregate:
      - get: bosh-dns-release
        trigger: true
      - get: envs
      - get: bosh-deployment
      - get: gcp-linux-stemcell
      - get: bosh-candidate-stemcell-windows
      - get: bosh-candidate-release
      - get: candidate-release
        trigger: true
    - do:
      - task: setup-env
        file: bosh-dns-release/ci/tasks/windows/setup-env.yml
        params:
          BBL_GCP_SERVICE_ACCOUNT_KEY: {{bbl_gcp_service_account_key_id}}
          BBL_GCP_REGION: us-central1
          BBL_STATE_DIR: windows2012/bbl-state
        ensure:
          put: envs
          params:
            repository: updated-bbl-state
      - task: windows
        file: bosh-dns-release/ci/tasks/windows/test-acceptance-windows.yml
        params:
          WINDOWS_OS_VERSION: windows2012R2
          BBL_STATE_SUBDIRECTORY: windows2012/bbl-state
        input_mapping:
          bbl-state: updated-bbl-state
        timeout: 1h
      # - task: windows-nameserver-disabled
      #   file: bosh-dns-release/ci/tasks/windows/test-acceptance-windows-nameserver-disabled.yml
      #   timeout: 1h
      # - task: windows-shared
      #   file: bosh-dns-release/ci/tasks/windows/test-acceptance-windows-shared.yml
      #   timeout: 1h
      ensure:
        task: destroy-env
        file: bosh-dns-release/ci/tasks/windows/destroy-env.yml
        input_mapping:
          bbl-state: updated-bbl-state
        params:
          BBL_GCP_SERVICE_ACCOUNT_KEY: {{bbl_gcp_service_account_key_id}}
          BBL_STATE_DIR: windows2012/bbl-state
        ensure:
          put: envs
          params:
            repository: cleanup-bbl-state
            rebase: true

- name: test-acceptance-windows2016
  public: true
  serial: true
  serial_groups:
  - windows-acceptance-env
  plan:
    - aggregate:
      - get: bosh-dns-release
        trigger: true
      - get: envs
      - get: bosh-deployment
      - get: gcp-linux-stemcell
      - get: bosh-candidate-stemcell-windows2016
      - get: bosh-candidate-release
      - get: candidate-release
        trigger: true
    - do:
      - task: setup-env
        file: bosh-dns-release/ci/tasks/windows/setup-env.yml
        params:
          BBL_GCP_SERVICE_ACCOUNT_KEY: {{bbl_gcp_service_account_key_id}}
          BBL_GCP_REGION: us-central1
          BBL_STATE_DIR: windows2016/bbl-state
        ensure:
          put: envs
          params:
            repository: updated-bbl-state
      - task: windows
        file: bosh-dns-release/ci/tasks/windows/test-acceptance-windows.yml
        params:
          WINDOWS_OS_VERSION: windows2016
          BBL_STATE_SUBDIRECTORY: windows2016/bbl-state
        input_mapping:
          bosh-candidate-stemcell-windows: bosh-candidate-stemcell-windows2016
          bbl-state: updated-bbl-state
        timeout: 1h
      # - task: windows-nameserver-disabled
      #   file: bosh-dns-release/ci/tasks/windows/test-acceptance-windows-nameserver-disabled.yml
      #   params:
      #     WINDOWS_OS_VERSION: windows2016
      #   input_mapping:
      #     bosh-candidate-stemcell-windows: bosh-candidate-stemcell-windows2016
      #   timeout: 1h
      # - task: windows-shared
      #   file: bosh-dns-release/ci/tasks/windows/test-acceptance-windows-shared.yml
      #   params:
      #     WINDOWS_OS_VERSION: windows2016
      #   input_mapping:
      #     bosh-candidate-stemcell-windows: bosh-candidate-stemcell-windows2016
      #   timeout: 1h
      ensure:
        task: destroy-env
        file: bosh-dns-release/ci/tasks/windows/destroy-env.yml
        input_mapping:
          bbl-state: updated-bbl-state
        params:
          BBL_GCP_SERVICE_ACCOUNT_KEY: {{bbl_gcp_service_account_key_id}}
          BBL_STATE_DIR: windows2016/bbl-state
        ensure:
          put: envs
          params:
            repository: cleanup-bbl-state
            rebase: true

resources:
- name: bosh-dns-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/bosh-dns-release
    branch: windows-bbl
    private_key: {{github_deployment_key}}
    ignore_paths:
    - ci/docker

- name: candidate-release
  type: s3
  source:
    bucket: {{candidate_release_bucket}}
    access_key_id: {{candidate_release_access_key_id}}
    secret_access_key: {{candidate_release_secret_access_key}}
    versioned_file: "bosh-dns-dev-release.tgz"

- name: bosh-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-deployment
    branch: master

- name: bosh-candidate-stemcell-windows
  type: s3
  source:
    region_name: us-east-2
    bucket: bosh-windows-stemcells-production
    regexp: light-bosh-stemcell-(.+)-google-kvm-windows2012R2-go_agent.tgz

- name: bosh-candidate-stemcell-windows2016
  type: s3
  source:
    bucket: bosh-windows-stemcells-production
    regexp: 1709/light-bosh-stemcell-(.+)-google-kvm-windows2016-go_agent.tgz
    region_name: us-east-2

- name: bosh-candidate-release
  type: s3
  source:
    bucket: bosh-candidate-release-tarballs
    versioned_file: bosh-dev-release.tgz

- name: gcp-linux-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-trusty-go_agent

- name: envs
  type: git
  source:
    branch: windows-bbl
    uri: git@github.com:cloudfoundry/dns-release-ci-envs.git
    private_key: {{envs_private_key}}
