
[[dependencies]]
  branch = "master"
  name = "github.com/cloudfoundry/bosh-utils"

[[dependencies]]
  branch = "master"
  name = "github.com/onsi/ginkgo"

[[dependencies]]
  branch = "master"
  name = "github.com/onsi/gomega"

[[dependencies]]
  branch = "master"
  name = "github.com/rcrowley/go-metrics"

[[dependencies]]
  branch = "master"
  name = "code.cloudfoundry.org/clock"
