---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
  - name: bbl-state
  - name: bosh-dns-release

outputs: []

params:
  BBL_STATE_SUBDIRECTORY: test-stress/bbl-state

run:
  path: bosh-dns-release/ci/tasks/test-stress/clean-up.sh
