---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
  - name: bbl-state
  - name: bosh-deployment
  - name: bosh-docker-cpi-release
  - name: bosh-dns-release
  - name: stemcell

outputs:
  - name: inner-bosh-vars

params:
  BBL_STATE_SUBDIRECTORY: test-stress/bbl-state

run:
  path: bosh-dns-release/ci/tasks/test-stress/deploy-inner-bosh.sh
